name: Publish Version

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # Build dependencies
            - name: Install XMake
              run: choco install xmake -y

            - name: Install NASM
              run: choco install nasm -y

            - name: Install Deno
              run: choco install deno -y

            # Refresh env
            - name: BLEH
              run: echo "C:\ProgramData\chocolatey\lib\deno\tools" >> $Env:GITHUB_PATH

            # Bump mod version
            - name: Get mod version
              id: get_version
              shell: powershell
              run: |
                Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
                refreshenv
                $NEW_VERSION = deno run --allow-read --allow-write .github/workflows/VersionTools.ts
                echo "NEW_VERSION=$NEW_VERSION" >> $env:GITHUB_ENV
                
            - name: Push bumped version
              shell: powershell
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git add $env:FILE_PATH
                git commit -m "Bump version to $env:NEW_VERSION"
                git push
                env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Build
              run: |
                xmake f -y --automated_build=y
                xmake
              shell: powershell

            - name: Zip dist folder
              run: |
                Compress-Archive -Path "dist/*" -DestinationPath "Offhand.zip"